import { MenuData } from '@/types/menu'

export const menuData = {
  hotel: {
    name: "The Aurelius",
    tagline: "Culinary Excellence Since 1923",
    address: "12 Golden Crescent, Mumbai 400001",
    phone: "+91 22 6699 0000",
    email: "dining@theaurelius.com",
    primaryColor: "#B8933A",
    accentColor: "#2C1810",
  } as const,
  lastUpdated: "2024-01-15",
  categories: [
    {
      id: "breakfast",
      name: "Breakfast",
      nameHi: "नाश्ता",
      nameGu: "નાસ્તો",
      description: "Morning indulgences to start your day",
      descriptionHi: "अपने दिन को शुरू करने के लिए सुबह के व्यंजन",
      descriptionGu: "તમારો દિવસ શરૂ કરવા માટે સવારનાં આનંદો",
      icon: "☀️",
      items: [
        {
          id: "b1",
          name: "Aurelius Grand Breakfast",
          nameHi: "ऑरेलियस ग्रैंड नाश्ता",
          nameGu: "ઓરેલિયસ ગ્રાન્ડ નાસ્તો",
          description: "Two farm eggs any style, grilled heritage tomatoes, artisan sourdough, selection of house preserves, and freshly squeezed orange juice",
          descriptionHi: "दो खेत के अंडे किसी भी शैली में, ग्रिल किए गए विरासत टमाटर, कारीगर खट्टी रोटी, घर के संरक्षण का चयन, और ताजा निचोड़ा हुआ संतरे का रस",
          descriptionGu: "બે ખેતરના ઈંડા કોઈપણ શૈલીમાં, ગ્રીલ કરેલા વારસાની ટમેટો, કારીગર ખોળી, ઘર સંરક્ષણ પસંદગી, અને તાજા નીચોવવામાં આવેલો નારંગીનો રસ",
          price: 1200,
          category: "breakfast",
          image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",
          tags: ["signature", "hearty"],
          available: true,
          featured: true,
          vegetarian: true,
          calories: 680,
          prepTime: "15 min"
        },
        {
          id: "b2",
          name: "Masala Omelette",
          nameHi: "मसाला ऑमलेट",
          nameGu: "મસાલો ઑમલેટ",
          description: "Three-egg omelette with green chillies, onions, tomatoes, fresh coriander, served with buttered toast and chai",
          descriptionHi: "तीन अंडे की ऑमलेट हरी मिर्च, प्याज, टमाटर, ताजी धनिया के साथ, मक्खन वाली रोटी और चाय के साथ परोसी जाती है",
          descriptionGu: "ત્રણ ઈંડાનો ઑમલેટ લીલી મરચ, પ્યાજ, ટમેટો, તાજુ ધાણું સાથે, માખણવાળી ટોસ્ટ અને ચાય સાથે પરોવવામાં આવે છે",
          price: 650,
          category: "breakfast",
          image: "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600&q=80",
          tags: ["local", "spicy"],
          available: true,
          vegetarian: true,
          spicy: true,
          calories: 420,
          prepTime: "12 min"
        },
        {
          id: "b3",
          name: "Avocado Toast",
          nameHi: "एवोकाडो टोस्ट",
          nameGu: "એવોકાડો ટોસ્ટ",
          description: "Smashed Alphonso avocado on charcoal sourdough, poached egg, microgreens, everything bagel seasoning",
          descriptionHi: "चारकोल खट्टी रोटी पर कुचला हुआ अल्फांसो एवोकाडो, उबला अंडा, माइक्रोग्रीन्स, सब कुछ बेगल सीजनिंग",
          descriptionGu: "ચારકોલ સોર્ડો પર કચમાધું આલ્ફોન્સો એવોકાડો, પોશ ઇંડો, માઈક્રોગ્રીન્સ, બધું બેગલ મસાલો",
          price: 880,
          category: "breakfast",
          image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=600&q=80",
          tags: ["healthy", "trending"],
          available: true,
          vegetarian: true,
          glutenFree: false,
          calories: 380,
          prepTime: "10 min"
        },
        {
          id: "b4",
          name: "Overnight Steel-Cut Oats",
          nameHi: "रातभर इस्पात-कट ओट्स",
          nameGu: "રાત ભર સ્ટીલ-કટ ઓટ્સ",
          description: "Slow-cooked rolled oats with coconut milk, fresh mango, toasted coconut, honey drizzle",
          descriptionHi: "नारियल के दूध के साथ धीमी आँच पर पकाई गई लुढ़की हुई जई, ताजा आम, भुनी हुई नारियल, शहद की बूंदें",
          descriptionGu: "નારિયલ દૂધ સાથે ધીમે ધીમે રાંધેલા રોલ્ડ ઓટ્સ, તાજું આમ, ટોસ્ટેડ નારિયલ, શહદ ટપક",
          price: 520,
          category: "breakfast",
          image: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600&q=80",
          tags: ["healthy", "vegan"],
          available: true,
          vegetarian: true,
          glutenFree: true,
          calories: 310,
          prepTime: "5 min"
        }
      ]
    },
    {
      id: "starters",
      name: "Starters",
      nameHi: "स्टार्टर्स",
      nameGu: "સ્ટાર્ટર્સ",
      description: "Begin your culinary journey",
      descriptionHi: "अपनी पाकशिल्प यात्रा शुरू करें",
      descriptionGu: "તમારી પાકશિલ્પ યાત્રા શરૂ કરો",
      icon: "🌿",
      items: [
        {
          id: "s1",
          name: "Burrata & Heritage Tomato",
          nameHi: "बुराटा और विरासत टमाटर",
          nameGu: "બુરાતા અને વારસાની ટમેટો",
          description: "Imported Italian burrata, heirloom tomatoes, aged balsamic, fresh basil oil, maldon salt",
          descriptionHi: "आयात किया गया इतालवी बुराटा, विरासत टमाटर, उम्र बालसामिक, ताजी तुलसी का तेल, मल्डन नमक",
          descriptionGu: "આયાત કરેલો ઈટાલિયન બુરાતા, વારસાની ટમેટો, વયસ્ક બાલસેમિક, તાજી તુલસી તેલ, માલ્ડન મીठ",
          price: 1450,
          category: "starters",
          image: "https://images.unsplash.com/photo-1618666012174-83b441c0bc76?w=600&q=80",
          tags: ["signature", "imported"],
          available: true,
          featured: true,
          vegetarian: true,
          glutenFree: true,
          calories: 340,
          prepTime: "8 min"
        },
        {
          id: "s2",
          name: "Tandoori Prawns",
          nameHi: "तंदूरी झींगे",
          nameGu: "તંદૂરી ઝીંગા",
          description: "Tiger prawns marinated in saffron yogurt, char-grilled in tandoor, served with mint chutney and pickled onions",
          descriptionHi: "बाघ झींगे केसर दही में अचार डाले गए, तंदूर में कोयले पर ग्रिल किए गए, पुदीने की चटनी और अचार प्याज के साथ परोसे गए",
          descriptionGu: "બાઘ ઝીંગા કેસર દહીમાં મેરીનેટ કરેલા, તંદૂરમાં કોલસા પર ગ્રીલ કરેલા, પુદીનાની ચટણી અને અચાર પ્યાજ સાથે પરોવવામાં આવે છે",
          price: 1800,
          category: "starters",
          image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80",
          tags: ["seafood", "tandoor"],
          available: true,
          featured: true,
          spicy: true,
          calories: 280,
          prepTime: "20 min"
        },
        {
          id: "s3",
          name: "Truffle Arancini",
          nameHi: "ट्रफल अरांसिनी",
          nameGu: "ટ્રફલ અરાનસીની",
          description: "Crispy risotto balls filled with black truffle, Parmigiano-Reggiano, served with truffle aioli",
          descriptionHi: "काली ट्रफल, पर्मिजियानो-रेजिआनो से भरी हुई कुरकुरी रिसोट्टो गेंदें, ट्रफल एओली के साथ परोसी जाती हैं",
          descriptionGu: "કાળા ટ્રફલ, પર્મીજિયાનો-રેજીનો થી ભરેલા કુરકુરા રીસોટ્ટો બોલ, ટ્રફલ એોલી સાથે પરોવવામાં આવે છે",
          price: 980,
          category: "starters",
          image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80",
          tags: ["truffle", "italian"],
          available: true,
          vegetarian: true,
          calories: 420,
          prepTime: "15 min"
        },
        {
          id: "s4",
          name: "Soup of the Day",
          nameHi: "दिन का सूप",
          nameGu: "આજનો સૂપ",
          description: "Chef's seasonal creation, freshly crafted daily with the finest market ingredients",
          descriptionHi: "शेफ की मौसमी रचना, सर्वोत्तम बाजार सामग्री के साथ दैनिक ताजा तैयार",
          descriptionGu: "શેફની મौસમી રચના, સર્વોત્તમ બાજાર સામગ્રી સાથે દૈનિક તાજા તૈયાર",
          price: 480,
          category: "starters",
          image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
          tags: ["seasonal", "daily"],
          available: true,
          vegetarian: true,
          prepTime: "10 min"
        }
      ]
    },
    {
      id: "mains",
      name: "Main Course",
      nameHi: "मुख्य कोर्स",
      nameGu: "મુખ્ય કોર્સ",
      description: "The heart of our kitchen",
      descriptionHi: "हमारी रसोई का दिल",
      descriptionGu: "અમારી રસોઈનું હૃદય",
      icon: "🍽️",
      items: [
        {
          id: "m1",
          name: "Butter Chicken",
          nameHi: "मक्खन चिकन",
          nameGu: "માખણ ચિકન",
          description: "Slow-cooked chicken in velvety tomato-cream sauce with house-blend spices, served with laccha paratha and saffron rice",
          descriptionHi: "रेशमी टमाटर-क्रीम सॉस में धीमी आँच पर पकाई गई मुर्गी, घर के मिश्रित मसालों के साथ, लच्छा पराठा और केसर चावल के साथ परोसी जाती है",
          descriptionGu: "પલાદી ટમેટો-ક્રીમ સૉસમાં ધીમે ધીમે રાંધેલો ચિકન, હોમ-બ્લેન્ડ મસાલા સાથે, લચ્છા પરાઠો અને કેસર ચોખા સાથે પરોવવામાં આવે છે",
          price: 1650,
          category: "mains",
          image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&q=80",
          tags: ["signature", "indian", "bestseller"],
          available: true,
          featured: true,
          calories: 780,
          prepTime: "25 min"
        },
        {
          id: "m2",
          name: "Norwegian Salmon",
          nameHi: "नॉर्वेजियन सैल्मन",
          nameGu: "નૉર્વેજીયન સૈલ્મન",
          description: "Pan-seared Atlantic salmon, lemon beurre blanc, asparagus, baby potatoes, dill oil",
          descriptionHi: "पैन-सीयर अटलांटिक सैल्मन, नींबू बेउरे ब्लैंक, शतावरी, बच्चे आलू, डिल तेल",
          descriptionGu: "પેન-સીયર્ડ અટલાંટિક સૈલ્મન, લીમોન બ્યુરે બ્લાંક, એસ્પેરાગસ, બેબી આલૂ, ડિલ તેલ",
          price: 2200,
          category: "mains",
          image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&q=80",
          tags: ["seafood", "healthy", "imported"],
          available: true,
          featured: true,
          glutenFree: true,
          calories: 520,
          prepTime: "20 min"
        },
        {
          id: "m3",
          name: "Wagyu Beef Tenderloin",
          nameHi: "वाग्यु बीफ टेंडरलॉइन",
          nameGu: "વાગ્યુ બીફ ટેન્ડરલોઈન",
          description: "250g Australian Wagyu MB5+, truffle butter, bone marrow jus, roasted garlic mash, seasonal vegetables",
          descriptionHi: "250 ग्राम ऑस्ट्रेलियन वाग्यु MB5+, ट्रफल मक्खन, हड्डी का मज्जा रस, भुनी हुई लहसुन की प्यूरी, मौसमी सब्जियाँ",
          descriptionGu: "250 ગ્રામ ઓસ્ટ્રેલીયન વાગ્યુ MB5+, ટ્રફલ માખણ, હાડકાનો મજ્જો જસ, ટોસ્ટેડ લસણ મેશ, સીઝનલ શાકભાજી",
          price: 4800,
          category: "mains",
          image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80",
          tags: ["premium", "wagyu", "signature"],
          available: true,
          featured: true,
          glutenFree: true,
          calories: 920,
          prepTime: "30 min"
        },
        {
          id: "m4",
          name: "Wild Mushroom Risotto",
          nameHi: "जंगली मशरूम रिसोट्टो",
          nameGu: "જંગલી મશરૂમ રીસોટ્ટો",
          description: "Carnaroli rice, porcini, chanterelle, truffle oil, aged Parmigiano, crispy sage",
          descriptionHi: "कारनारोली चावल, पोरसीनी, चेंटरेल, ट्रफल तेल, उम्र पर्मिजियानो, कुरकुरी ऋषि",
          descriptionGu: "કારનારોલી ચોખા, પોર્સીની, ચેંટરેલ, ટ્રફલ તેલ, વયસ્ક પર્મીજિયાનો, કુરકુરા સેજ",
          price: 1380,
          category: "mains",
          image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&q=80",
          tags: ["vegetarian", "italian", "truffle"],
          available: true,
          vegetarian: true,
          glutenFree: true,
          calories: 580,
          prepTime: "22 min"
        },
        {
          id: "m5",
          name: "Dal Makhani",
          nameHi: "दाल मखानी",
          nameGu: "દાલ મખાણી",
          description: "Black lentils slow-cooked overnight with tomato, cream and house spices. A 24-hour labour of love",
          descriptionHi: "काली दाल को रातभर टमाटर, क्रीम और घर के मसालों के साथ धीमी आँच पर पकाया जाता है। 24 घंटे की प्रेम की मेहनत",
          descriptionGu: "કાળી દાલ રાત ભર ટમેટો, ક્રીમ અને ઘર મસાલા સાથે ધીમે ધીમે રાંધવામાં આવે છે. 24 કલાકની પ્રેમની મેહનત",
          price: 880,
          category: "mains",
          image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80",
          tags: ["indian", "vegetarian", "slow-cook"],
          available: true,
          vegetarian: true,
          calories: 480,
          prepTime: "10 min"
        }
      ]
    },
    {
      id: "desserts",
      name: "Desserts",
      nameHi: "मिठाई",
      nameGu: "મીઠાઈ",
      description: "Sweet endings crafted with love",
      descriptionHi: "प्रेम से बनाई गई मीठी समाप्ति",
      descriptionGu: "પ્રેમથી બનાવેલો મીઠો અંત",
      icon: "🍮",
      items: [
        {
          id: "d1",
          name: "Dark Chocolate Fondant",
          nameHi: "डार्क चॉकलेट फॉन्डेंट",
          nameGu: "ડાર્ક ચોકલેટ ફોંડેંટ",
          description: "Valrhona 70% chocolate lava cake, Tahitian vanilla ice cream, gold dust, raspberry coulis",
          descriptionHi: "वाल्रोना 70% चॉकलेट लावा केक, ताहिती वैनिला आइसक्रीम, सोने की धूल, रास्पबेरी कूली",
          descriptionGu: "વાલ્રોના 70% ચોકલેટ લાવા કેક, તાહિતીયન વેનિલા આઈસક્રીમ, સોনાની ધૂળ, રાસ્પબેરી કૂલી",
          price: 980,
          category: "desserts",
          image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&q=80",
          tags: ["chocolate", "warm", "signature"],
          available: true,
          featured: true,
          vegetarian: true,
          calories: 520,
          prepTime: "18 min"
        },
        {
          id: "d2",
          name: "Mango Saffron Panna Cotta",
          nameHi: "आम केसर पन्ना कॉटा",
          nameGu: "આમ કેસર પન્ના કોટ્ટા",
          description: "Silky panna cotta infused with Kashmiri saffron, Alphonso mango coulis, pistachio brittle",
          descriptionHi: "कश्मीरी केसर से भरी हुई रेशमी पन्ना कॉटा, अल्फांसो आम कूली, पिस्ता कुरकुरा",
          descriptionGu: "કાશ્મીરી કેસર થી ભરેલો પલાદી પન્ના કોટ્ટા, અલ્ફોન્સો આમ કૂલી, પિસ્તો બ્રિટલ",
          price: 720,
          category: "desserts",
          image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80",
          tags: ["seasonal", "indian-fusion"],
          available: true,
          vegetarian: true,
          glutenFree: true,
          calories: 340,
          prepTime: "5 min"
        },
        {
          id: "d3",
          name: "Gulab Jamun Trifle",
          nameHi: "गुलाब जामुन ट्राइफल",
          nameGu: "ગુલાબ જામુન ટ્રાઈફલ",
          description: "Classic gulab jamun reimagined as a trifle with cardamom custard, rose chantilly, pistachio crumble",
          descriptionHi: "क्लासिक गुलाब जामुन को इलायची कस्टर्ड, गुलाब चेंटिली, पिस्ता कुरकुरा के साथ ट्राइफल के रूप में फिर से तैयार किया गया",
          descriptionGu: "ક્લાસિક ગુલાબ જામુનને ઇલાયચી કસ્ટર્ડ, રોઝ ચેંટિલી, પિસ્તો ક્રમ્બલ સાથે ટ્રાઈફલ તરીકે ફરી કલ્પાયો",
          price: 650,
          category: "desserts",
          image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&q=80",
          tags: ["indian", "fusion", "trending"],
          available: true,
          vegetarian: true,
          calories: 480,
          prepTime: "8 min"
        }
      ]
    },
    {
      id: "drinks",
      name: "Beverages",
      nameHi: "पेय",
      nameGu: "પીણાં",
      description: "Curated drinks for every mood",
      descriptionHi: "हर मूड के लिए क्यूरेटेड पेय",
      descriptionGu: "દરેક મૂડ માટે ક્યુરેટેડ પીણાં",
      icon: "🍹",
      items: [
        {
          id: "dr1",
          name: "Aurelius Signature Mocktail",
          nameHi: "ऑरेलियस सिग्नेचर मॉकटेल",
          nameGu: "ઓરેલિયસ સિગ્નેચર મોકટેલ",
          description: "House-crafted blend of passion fruit, rose water, lychee, topped with butterfly pea flower fizz",
          descriptionHi: "आवेग फल, गुलाब जल, लीची का घर-निर्मित मिश्रण, तितली मटर फूल फिज़ के साथ शीर्ष पर",
          descriptionGu: "પેશન ફ્રુટ, ગુલાબ જળ, લીચી ની ઘર-નિર્મિત બ્લેન્ડ, બટરફ્લાય પીઝ ફ્લાવર ફિઝ સાથે ટોપ",
          price: 480,
          category: "drinks",
          image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&q=80",
          tags: ["signature", "mocktail", "instagram"],
          available: true,
          featured: true,
          vegetarian: true,
          glutenFree: true,
          calories: 120
        },
        {
          id: "dr2",
          name: "Masala Chai",
          nameHi: "मसाला चाय",
          nameGu: "મસાલો ચાય",
          description: "Hand-blended Assam tea with ginger, cardamom, cinnamon, cloves, served with house biscotti",
          descriptionHi: "अदरक, इलायची, दालचीनी, लौंग के साथ हाथ से मिश्रित असम चाय, घर बिस्कॉटी के साथ परोसी जाती है",
          descriptionGu: "અદરક, ઇલાયચી, દાલચીની, લવિંગ સાથે હાથથી બ્લેન્ડેડ આસમ ચાય, ઘર બિસ્કોટી સાથે પરોવવામાં આવે છે",
          price: 220,
          category: "drinks",
          image: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600&q=80",
          tags: ["indian", "hot", "classic"],
          available: true,
          vegetarian: true,
          glutenFree: true,
          calories: 80
        },
        {
          id: "dr3",
          name: "Cold Press Juice",
          nameHi: "कोल्ड प्रेस जूस",
          nameGu: "કોલ્ડ પ્રેસ જ્યુસ",
          description: "Daily rotation of seasonal fruits and vegetables. Ask your server for today's blend",
          descriptionHi: "मौसमी फलों और सब्जियों का दैनिक रोटेशन। आज के ब्लेंड के लिए अपने सर्वर से पूछें",
          descriptionGu: "સીઝનલ ફ્રુટ્સ અને શાકભાજીનું દૈનિક રોટેશન. આજના બ્લેન્ડ માટે તમારા સર્વરને પૂછો",
          price: 380,
          category: "drinks",
          image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&q=80",
          tags: ["healthy", "fresh", "seasonal"],
          available: true,
          vegetarian: true,
          glutenFree: true,
          calories: 95
        },
        {
          id: "dr4",
          name: "Single Origin Espresso",
          nameHi: "सिंगल ऑरिजिन एस्प्रेसो",
          nameGu: "સિંગલ ઓરિજીન એસ્પ્રેસો",
          description: "Ethiopian Yirgacheffe beans, hand-selected and roasted in-house. Pure, bright, complex",
          descriptionHi: "इथियोपियाई येर्गाचेफ बीन्स, हाथ से चयनित और घर में भुनी हुई। शुद्ধ, चमकदार, जटिल",
          descriptionGu: "ઇથોપિયન યર્ગાચેફ બીન્સ, હાથ-પસંદ અને ઘર-રોસ્ટેડ. શુદ્ધ, તેજસ્વી, જટિલ",
          price: 280,
          category: "drinks",
          image: "https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=600&q=80",
          tags: ["coffee", "premium", "single-origin"],
          available: true,
          vegetarian: true,
          glutenFree: true,
          calories: 5
        }
      ]
    }
  ]
}